   library(limma)
   targets <- readTargets("targets2.txt")
    x <- read.maimages(targets, source="agilent.median",green.only=TRUE)
   y <- backgroundCorrect(x, method="normexp", offset=16)
   y <- normalizeBetweenArrays(y, method="quantile")
   y.ave <- avereps(y, ID=y$genes$ProbeName)
   f <- factor(targets$Condition, levels = unique(targets$Condition))
   design <- model.matrix(~0 + f)
   colnames(design) <- levels(f)
   fit <- lmFit(y, design)
   contrast.matrix <- makeContrasts("N_A-N_B", levels=design)
   fit2 <- contrasts.fit(fit, contrast.matrix)
   fit2 <- eBayes(fit2)
   output <- topTable(fit2, adjust="none", coef="N_A-N_B", genelist=y$genes, number=Inf)
   write.table(output, file="N_B-N_A.txt", sep="\t", quote=FALSE)
	 sub=subset(output,P.Value<0.05 & abs(logFC) >= 1.7)
	write.table(sub,"N_A-N_Bfiltered.txt",sep="\t")

	 sub=subset(output,adj.P.Val<0.05 & abs(logFC) >= 0.4)
		write.table(sub,"N_A-N_B_filter.txt",sep="\t")
